Repository ezsystems/ezplatform-admin-ui-modules, pull requests merged in 2018-03, with the labels that each got.

#54 EZP-28877: As a developer I would like to inject custom tabs configuration into the Universal Discovery module instance
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/universal.discovery.module.js
Labels: enhancement

#52 EZP-28878: Allow setting the icon of the Universal Discovery custom tab
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/universal.discovery.module.js
Labels: enhancement, ready-for-review

#55 EZP-28841: Content On the Fly v2
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/content-creator/content.creator.component.js
  src/modules/universal-discovery/components/content-creator/css/content.creator.component.css
  src/modules/universal-discovery/components/content-meta-preview/content.meta.preview.component.js
  src/modules/universal-discovery/components/create/create.choose.content.type.component.js
  src/modules/universal-discovery/components/create/create.choose.language.component.js
  src/modules/universal-discovery/components/create/create.component.js
  src/modules/universal-discovery/components/create/css/create.choose.content.type.component.css
  src/modules/universal-discovery/components/create/css/create.choose.language.component.css
  src/modules/universal-discovery/components/create/css/create.component.css
  src/modules/universal-discovery/components/finder/css/finder.tree.leaf.component.css
  src/modules/universal-discovery/components/finder/finder.component.js
  src/modules/universal-discovery/components/finder/finder.tree.branch.component.js
  src/modules/universal-discovery/components/finder/finder.tree.leaf.component.js
  src/modules/universal-discovery/components/tab-content/create.panel.component.js
  src/modules/universal-discovery/components/tab-content/css/create.panel.component.css
  src/modules/universal-discovery/components/tab-content/finder.panel.component.js
  src/modules/universal-discovery/css/universal.discovery.module.css
  src/modules/universal-discovery/services/universal.discovery.service.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: enhancement

#57 EZP-28727: Edit button from Multi-file upload does not redirect to Edit form
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/common/services/common.service.js
  src/modules/common/services/content.service.js
  src/modules/common/services/content.type.service.js
  src/modules/common/services/location.service.js
  src/modules/multi-file-upload/components/upload-list/upload.item.component.js
  src/modules/sub-items/sub.items.module.js
Labels: bug, ready-for-qa, ready-for-review

#56 EZP-28922: Multi-file upload modal design consistency
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/common/popup/css/popup.component.css
  src/modules/multi-file-upload/components/drop-area/css/drop.area.component.css
  src/modules/multi-file-upload/components/progress-bar/css/progress.bar.component.css
  src/modules/multi-file-upload/components/upload-list/css/upload.item.component.css
  src/modules/multi-file-upload/components/upload-popup/css/upload.popup.component.css
Labels: QA done

#59 EZP-28362: Display Language name and not language code.
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/sub-items/components/sub-items-list/sub.items.list.component.js
  src/modules/sub-items/components/table-view/css/table.view.item.component.css
  src/modules/sub-items/components/table-view/table.view.component.js
  src/modules/sub-items/components/table-view/table.view.item.component.js
  src/modules/sub-items/sub.items.module.js
  src/modules/universal-discovery/components/content-meta-preview/content.meta.preview.component.js
  src/modules/universal-discovery/components/content-meta-preview/css/content.meta.preview.component.css
Labels: QA done, bug

#60 EZP-29009: On empty containers SubItems performs 2 fetch requests
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  src/modules/sub-items/sub.items.module.js
Labels: QA done, bug, ready-for-review

#61 EZP-29010: Move Content on the Fly common configuration to root namespace od AdminUI config
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/sub-items/components/table-view/table.view.item.component.js
  src/modules/universal-discovery/components/content-meta-preview/content.meta.preview.component.js
  src/modules/universal-discovery/components/create/create.choose.language.component.js
  src/modules/universal-discovery/components/create/create.component.js
  src/modules/universal-discovery/components/tab-content/create.panel.component.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: bug
