Repository ezsystems/ezplatform-admin-ui-modules, pull requests merged in 2018-12, with the labels that each got.

#112 EZP-29714: As an Editor, I want to use pagination in the sub-items widgets
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/translations/sub_items.en.xliff
  src/modules/sub-items/components/grid-view/grid.view.component.js
  src/modules/sub-items/components/load-more/css/load.more.component.css
  src/modules/sub-items/components/load-more/load.more.component.js
  src/modules/sub-items/components/pagination/pagination.button.component.js
  src/modules/sub-items/components/pagination/pagination.component.js
  src/modules/sub-items/components/sub-items-list/sub.items.list.component.js
  src/modules/sub-items/components/table-view/table.view.component.js
  src/modules/sub-items/components/table-view/table.view.item.component.js
  src/modules/sub-items/components/view-switcher/css/view.switcher.component.css
  src/modules/sub-items/css/sub.items.module.css
  src/modules/sub-items/sub.items.module.js
Labels: Feature, QA approved

#116 EZP-29842: Implement content create permissions check in MFU
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/translations/multi_file_upload.en.xliff
  package.json
  src/modules/common/tooltip-popup/tooltip.popup.component.js
  src/modules/multi-file-upload/components/upload-list/upload.item.component.js
  src/modules/multi-file-upload/components/upload-list/upload.list.component.js
  src/modules/multi-file-upload/css/multi.file.upload.module.css
  src/modules/multi-file-upload/multi.file.upload.module.js
  src/modules/multi-file-upload/services/multi.file.upload.service.js
Labels: Feature, QA approved, Ready for review

#118 EZP-29873: "Cannot set property 'CurrentVersion' of null" notification when user click Bookmarks tab in UDW
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/universal.discovery.module.js
Labels: Bug, QA approved, Ready for MERGE

#117 EZP-29872: Unnecessary duplication of the file size in multi-file upload
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/multi-file-upload/components/drop-area/drop.area.component.js
Labels: Bug, QA approved, Ready for MERGE

#113 EZP-29747: As an editor, I want to see a list of content items impossible to delete
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/translations/sub_items.en.xliff
  src/modules/sub-items/services/bulk.service.js
  src/modules/sub-items/sub.items.module.js
Labels: Feature, QA approved, Ready for MERGE

#122 EZP-29965: Search in UDW does not show translated Content Type name
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/content-table/content.table.item.component.js
Labels: Bug, QA approved, Ready for review

#123 EZP-29966: Content Type is not translated in Subitems list view
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/sub-items/components/table-view/table.view.item.component.js
Labels: Bug, QA approved, Ready for review

#124 EZP-29968: Error 500 for bulk delete/move
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/sub-items/services/bulk.service.js
Labels: Bug, Ready for review
