Repository ezsystems/ezplatform-admin-ui-modules, pull requests merged in 2018-07, with the labels that each got.

#82 UDW code improvements
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  package.json
  src/modules/universal-discovery/components/bookmarks/bookmarks.component.js
  src/modules/universal-discovery/components/content-meta-preview/content.meta.preview.component.js
  src/modules/universal-discovery/components/tab-content/bookmarks.panel.component.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: enhancement, ready-for-review

#83 Implemented more performant deep clone helper
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/common/helpers/clone.helper.js
  src/modules/common/helpers/deep.clone.helper.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: QA done, enhancement

#85 EZP-29383: Error when handling errors in Bookmarks tab in the Universal Discovery
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/services/bookmark.service.js
Labels: QA done, bug, ready-for-review

#84 EZP-29381: Selected item becomes unselected for a moment while browsing content in UDW
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/finder/css/finder.tree.branch.component.css
  src/modules/universal-discovery/components/finder/finder.component.js
  src/modules/universal-discovery/components/finder/finder.tree.branch.component.js
  src/modules/universal-discovery/components/finder/finder.tree.leaf.component.js
Labels: QA done, bug, ready-for-review

#80 EZP-29155: Priority buttons work in the same way
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  src/modules/sub-items/components/table-view/table.view.item.component.js
Labels: QA done

#86 Coding standards fixes
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/common/popup/popup.component.js
  src/modules/common/services/common.service.js
  src/modules/common/services/content.service.js
  src/modules/common/services/content.type.service.js
  src/modules/common/services/location.service.js
  src/modules/multi-file-upload/components/drop-area/drop.area.component.js
  src/modules/multi-file-upload/components/progress-bar/progress.bar.component.js
  src/modules/multi-file-upload/components/upload-list/upload.item.component.js
  src/modules/multi-file-upload/components/upload-list/upload.list.component.js
  src/modules/multi-file-upload/components/upload-popup/upload.popup.component.js
  src/modules/multi-file-upload/helpers/text.helper.js
  src/modules/multi-file-upload/multi.file.upload.module.js
  src/modules/multi-file-upload/services/multi.file.upload.service.js
  src/modules/sub-items/components/grid-view/grid.view.component.js
  src/modules/sub-items/components/grid-view/grid.view.item.component.js
  src/modules/sub-items/components/load-more/load.more.component.js
  src/modules/sub-items/components/no-items/no.items.component.js
  src/modules/sub-items/components/sub-items-list/sub.items.list.component.js
  src/modules/sub-items/components/table-view/table.view.component.js
  src/modules/sub-items/components/table-view/table.view.item.component.js
  src/modules/sub-items/components/view-switcher/view.switcher.component.js
  src/modules/sub-items/services/sub.items.service.js
  src/modules/sub-items/sub.items.module.js
  src/modules/universal-discovery/components/content-creator/content.creator.component.js
  src/modules/universal-discovery/components/content-table/content.table.component.js
  src/modules/universal-discovery/components/create/choose.content.type.component.js
  src/modules/universal-discovery/components/create/choose.language.component.js
  src/modules/universal-discovery/components/create/create.component.js
  src/modules/universal-discovery/components/search/search.pagination.component.js
  src/modules/universal-discovery/components/search/search.results.component.js
  src/modules/universal-discovery/components/search/search.results.item.component.js
  src/modules/universal-discovery/components/selected-content/selected.content.component.js
  src/modules/universal-discovery/components/selected-content/selected.content.item.component.js
  src/modules/universal-discovery/components/selected-content/selected.content.popup.component.js
  src/modules/universal-discovery/components/tab-content/bookmarks.panel.component.js
  src/modules/universal-discovery/components/tab-content/create.panel.component.js
  src/modules/universal-discovery/components/tab-content/finder.panel.component.js
  src/modules/universal-discovery/components/tab-content/search.panel.component.js
  src/modules/universal-discovery/components/tab-content/tab.content.panel.component.js
  src/modules/universal-discovery/components/tab-nav/tab.nav.item.component.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: enhancement

#88 EZP-29371: Error 500 for empty search in UDW
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/search/css/search.component.css
  src/modules/universal-discovery/components/search/search.component.js
Labels: QA done, bug, ready-for-review

#78 EZP-29314: Lots of error messages after clicking fast bookmark button
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/bookmarks/bookmarks.component.js
  src/modules/universal-discovery/components/content-meta-preview/content.meta.preview.component.js
  src/modules/universal-discovery/components/tab-content/bookmarks.panel.component.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: QA done, bug

#91 EZP-29401: Incorrect selection color while creating content in the Universal Discovery
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/create/css/choose.content.type.component.css
Labels: bug, ready-for-qa, ready-for-review

#93 EZP-29424: I want Confirmed items in UDW to be differentiated from the background
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/selected-content/css/selected.content.component.css
Labels: enhancement, ready-for-review

#94 EZP-29182/EZP-29187: Improvements in Universal Discovery Widget single and multi selection
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/bookmarks/bookmarks.component.js
  src/modules/universal-discovery/components/content-meta-preview/content.meta.preview.component.js
  src/modules/universal-discovery/components/content-meta-preview/css/content.meta.preview.component.css
  src/modules/universal-discovery/components/content-table/content.table.component.js
  src/modules/universal-discovery/components/content-table/content.table.item.component.js
  src/modules/universal-discovery/components/content-table/css/content.table.item.component.css
  src/modules/universal-discovery/components/finder/css/finder.tree.leaf.component.css
  src/modules/universal-discovery/components/finder/finder.component.js
  src/modules/universal-discovery/components/finder/finder.tree.branch.component.js
  src/modules/universal-discovery/components/finder/finder.tree.leaf.component.js
  src/modules/universal-discovery/components/search/search.component.js
  src/modules/universal-discovery/components/select-content-button/css/select.content.button.component.css
  src/modules/universal-discovery/components/select-content-button/select.content.button.component.js
  src/modules/universal-discovery/components/tab-content/bookmarks.panel.component.js
  src/modules/universal-discovery/components/tab-content/create.panel.component.js
  src/modules/universal-discovery/components/tab-content/finder.panel.component.js
  src/modules/universal-discovery/components/tab-content/search.panel.component.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: QA done, enhancement

#90 EZP-28890: eZ Platform v2 i18n support in UDW, sub-items & file-upload module
  DependencyInjection/EzPlatformAdminUiModulesExtension.php
  Resources/config/bazinga_js_translation.yml
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/translations/multi_file_upload.en.xliff
  Resources/translations/sub_items.en.xliff
  Resources/translations/universal_discovery_widget.en.xliff
  src/modules/multi-file-upload/components/drop-area/drop.area.component.js
  src/modules/multi-file-upload/components/upload-list/upload.item.component.js
  src/modules/multi-file-upload/components/upload-popup/upload.popup.component.js
  src/modules/multi-file-upload/multi.file.upload.module.js
  src/modules/sub-items/components/grid-view/grid.view.component.js
  src/modules/sub-items/components/grid-view/grid.view.item.component.js
  src/modules/sub-items/components/load-more/load.more.component.js
  src/modules/sub-items/components/no-items/no.items.component.js
  src/modules/sub-items/components/sub-items-list/sub.items.list.component.js
  src/modules/sub-items/components/table-view/table.view.component.js
  src/modules/sub-items/components/table-view/table.view.item.component.js
  src/modules/sub-items/components/view-switcher/view.switcher.component.js
  src/modules/sub-items/sub.items.module.js
  src/modules/universal-discovery/components/bookmarks/bookmarks.component.js
  src/modules/universal-discovery/components/content-creator/content.creator.component.js
  src/modules/universal-discovery/components/content-meta-preview/content.meta.preview.component.js
  src/modules/universal-discovery/components/content-table/content.table.component.js
  src/modules/universal-discovery/components/content-table/content.table.header.component.js
  src/modules/universal-discovery/components/content-table/content.table.item.component.js
  src/modules/universal-discovery/components/content-table/content.table.pagination.component.js
  src/modules/universal-discovery/components/create/choose.content.type.component.js
  src/modules/universal-discovery/components/create/choose.language.component.js
  src/modules/universal-discovery/components/create/create.component.js
  src/modules/universal-discovery/components/finder/finder.component.js
  src/modules/universal-discovery/components/finder/finder.tree.branch.component.js
  src/modules/universal-discovery/components/search/search.component.js
  src/modules/universal-discovery/components/search/search.pagination.component.js
  src/modules/universal-discovery/components/search/search.results.component.js
  src/modules/universal-discovery/components/search/search.results.item.component.js
  src/modules/universal-discovery/components/selected-content/selected.content.component.js
  src/modules/universal-discovery/components/selected-content/selected.content.item.component.js
  src/modules/universal-discovery/components/tab-content/bookmarks.panel.component.js
  src/modules/universal-discovery/components/tab-content/create.panel.component.js
  src/modules/universal-discovery/components/tab-content/finder.panel.component.js
  src/modules/universal-discovery/components/tab-content/search.panel.component.js
  src/modules/universal-discovery/universal.discovery.module.js
  webpack.common.js
Labels: QA done, enhancement, ready-for-review

#96 EZP-29463: Confirmed items should not be visible if is single selection
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/universal.discovery.module.js
Labels: bug

#92 Code improvements
  .eslintrc.json
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  package.json
  src/modules/common/popup/popup.component.js
  src/modules/common/services/content.service.js
  src/modules/common/services/content.type.service.js
  src/modules/common/services/location.service.js
  src/modules/multi-file-upload/components/upload-list/upload.list.component.js
  src/modules/multi-file-upload/components/upload-popup/upload.popup.component.js
  src/modules/multi-file-upload/multi.file.upload.module.js
  src/modules/multi-file-upload/services/multi.file.upload.service.js
  src/modules/sub-items/components/grid-view/grid.view.component.js
  src/modules/sub-items/components/load-more/load.more.component.js
  src/modules/sub-items/components/sub-items-list/sub.items.list.component.js
  src/modules/sub-items/components/table-view/table.view.component.js
  src/modules/sub-items/components/table-view/table.view.item.component.js
  src/modules/sub-items/components/view-switcher/view.switcher.button.component.js
  src/modules/sub-items/components/view-switcher/view.switcher.component.js
  src/modules/sub-items/services/sub.items.service.js
  src/modules/sub-items/sub.items.module.js
  src/modules/universal-discovery/components/content-meta-preview/content.meta.preview.component.js
  src/modules/universal-discovery/components/content-table/content.table.component.js
  src/modules/universal-discovery/components/finder/finder.component.js
  src/modules/universal-discovery/components/finder/finder.tree.branch.component.js
  src/modules/universal-discovery/components/finder/finder.tree.leaf.component.js
  src/modules/universal-discovery/components/search/search.component.js
  src/modules/universal-discovery/components/search/search.results.component.js
  src/modules/universal-discovery/components/selected-content/selected.content.component.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: QA done, enhancement, ready-for-review

#95 EZP-29452: Rendering unused panels in Universal Discovery
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/universal.discovery.module.js
Labels: QA done, bug
