Repository ezsystems/ezplatform-admin-ui-modules, pull requests merged in 2018-10, with the labels that each got.

#103 EZP-29681: Clicking Confirmed items closes UDW
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/selected-content/selected.content.component.js
Labels: QA done, bug

#105 EZP-29622: Date is not changed on UDW
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/content-meta-preview/content.meta.preview.component.js
Labels: QA done, bug

#104 EZP-29621: Date is not changed on Sub-items list
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  src/modules/sub-items/components/table-view/table.view.item.component.js
Labels: QA done, bug

#108 EZP-29737: Invalid UDW container height after resizing window
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/universal.discovery.module.js
Labels: QA done, bug, ready-for-review

#110 EZP-29701: Select content button's outline is cut at the bottom
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/select-content-button/css/select.content.button.component.css
Labels: bug, ready-for-qa

#111 EZP-29746: Selected item blinking while loading its children in UDW
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/finder/finder.component.js
  src/modules/universal-discovery/components/finder/finder.tree.branch.component.js
  src/modules/universal-discovery/components/finder/finder.tree.leaf.component.js
  src/modules/universal-discovery/components/select-content-button/select.content.button.component.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: Bug, QA approved, Ready for review

#107 EZP-28067; EZP-29713: Implement bulk delete, bulk move
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/translations/sub_items.en.xliff
  Resources/translations/universal_discovery_widget.en.xliff
  src/modules/common/helpers/request.helper.js
  src/modules/common/icon/icon.js
  src/modules/common/popup/css/popup.component.css
  src/modules/common/popup/popup.component.js
  src/modules/common/tooltip-popup/css/tooltip.popup.component.css
  src/modules/common/tooltip-popup/tooltip.popup.component.js
  src/modules/multi-file-upload/components/upload-popup/css/upload.popup.component.css
  src/modules/multi-file-upload/components/upload-popup/upload.popup.component.js
  src/modules/sub-items/components/action-btn/action.btn.js
  src/modules/sub-items/components/action-btn/css/action.btn.css
  src/modules/sub-items/components/sub-items-list/sub.items.list.component.js
  src/modules/sub-items/components/table-view/css/table.view.component.css
  src/modules/sub-items/components/table-view/css/table.view.item.component.css
  src/modules/sub-items/components/table-view/table.view.component.js
  src/modules/sub-items/components/table-view/table.view.item.component.js
  src/modules/sub-items/css/sub.items.module.css
  src/modules/sub-items/services/bulk.service.js
  src/modules/sub-items/services/sub.items.service.js
  src/modules/sub-items/sub.items.module.js
  src/modules/universal-discovery/components/selected-content/css/selected.content.component.css
  src/modules/universal-discovery/components/selected-content/css/selected.content.popup.component.css
  src/modules/universal-discovery/components/selected-content/selected.content.popup.component.js
  src/modules/universal-discovery/services/bookmark.service.js
  src/modules/universal-discovery/services/universal.discovery.service.js
  webpack.common.js
Labels: Improvement, QA approved, Ready for MERGE
