Repository ezsystems/ezplatform-admin-ui-modules, pull requests merged in 2018-05, with the labels that each got.

#63 EZP-28936/EZP-29000/EZP-29001/EZP-29002/EZP-29003/EZP-29004/EZP-29005/EZP-29007 - Content on the Fly configuration
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/content-creator/css/content.creator.component.css
  src/modules/universal-discovery/components/create/choose.content.type.component.js
  src/modules/universal-discovery/components/create/choose.language.component.js
  src/modules/universal-discovery/components/create/create.choose.language.component.js
  src/modules/universal-discovery/components/create/create.component.js
  src/modules/universal-discovery/components/create/css/choose.content.type.component.css
  src/modules/universal-discovery/components/create/css/choose.language.component.css
  src/modules/universal-discovery/components/finder/css/finder.tree.branch.component.css
  src/modules/universal-discovery/components/finder/css/finder.tree.leaf.component.css
  src/modules/universal-discovery/components/finder/finder.component.js
  src/modules/universal-discovery/components/finder/finder.tree.branch.component.js
  src/modules/universal-discovery/components/finder/finder.tree.leaf.component.js
  src/modules/universal-discovery/components/tab-content/create.panel.component.js
  src/modules/universal-discovery/css/universal.discovery.module.css
  src/modules/universal-discovery/services/universal.discovery.service.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: QA done, enhancement

#65 EZP-29154: As a developer, I want to configure the number of sub-items displayed in the sub-items list
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  src/modules/sub-items/sub.items.module.js
Labels: QA done, ready-for-review

#64 Remove module doc files and link to developer doc
  README.md
  src/modules/multi-file-upload/module-usage.md
  src/modules/sub-items/module-usage.md
  src/modules/universal-discovery/module-usage.md
Labels: enhancement
