Repository ezsystems/ezplatform-admin-ui-modules, pull requests merged in 2018-06, with the labels that each got.

#67 EZP-29251: Expose field types values when selecting content with UDW
  .babelrc
  .eslintrc.json
  .prettierrc
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  package.json
  src/modules/universal-discovery/components/content-meta-preview/content.meta.preview.component.js
  src/modules/universal-discovery/components/content-meta-preview/css/content.meta.preview.component.css
  src/modules/universal-discovery/services/universal.discovery.service.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: QA done, enhancement, ready-for-review

#66 EZP-29148: As an editor I want to access my bookmarks from UDW
  .gitignore
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  package.json
  src/modules/common/helpers/compare.helper.js
  src/modules/common/services/notification.service.js
  src/modules/universal-discovery/components/bookmarks/bookmarks.component.js
  src/modules/universal-discovery/components/bookmarks/css/bookmarks.component.css
  src/modules/universal-discovery/components/content-meta-preview/content.meta.preview.component.js
  src/modules/universal-discovery/components/content-meta-preview/css/content.meta.preview.component.css
  src/modules/universal-discovery/components/content-table/content.table.component.js
  src/modules/universal-discovery/components/content-table/content.table.header.component.js
  src/modules/universal-discovery/components/content-table/content.table.item.component.js
  src/modules/universal-discovery/components/content-table/content.table.pagination.component.js
  src/modules/universal-discovery/components/content-table/css/content.table.component.css
  src/modules/universal-discovery/components/content-table/css/content.table.header.component.css
  src/modules/universal-discovery/components/content-table/css/content.table.item.component.css
  src/modules/universal-discovery/components/content-table/css/content.table.pagination.component.css
  src/modules/universal-discovery/components/create/create.component.js
  src/modules/universal-discovery/components/finder/finder.component.js
  src/modules/universal-discovery/components/search/search.component.js
  src/modules/universal-discovery/components/search/search.pagination.component.js
  src/modules/universal-discovery/components/search/search.results.component.js
  src/modules/universal-discovery/components/search/search.results.item.component.js
  src/modules/universal-discovery/components/selected-content/selected.content.component.js
  src/modules/universal-discovery/components/tab-content/bookmarks.panel.component.js
  src/modules/universal-discovery/components/tab-content/create.panel.component.js
  src/modules/universal-discovery/components/tab-content/css/bookmarks.panel.component.css
  src/modules/universal-discovery/helpers/request.helper.js
  src/modules/universal-discovery/services/bookmark.service.js
  src/modules/universal-discovery/services/universal.discovery.service.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: QA done

#69 Split Webpack configuration file into 3 files: common, prod., dev.
  package.json
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: enhancement, ready-for-review

#68 EZP-29302: UDW displays N/A instead of item's Content Type
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/common/helpers/clone.helper.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: QA done, bug, ready-for-review

#71 EZP-29319: I want to know that Confirmed items in UDW are clickable
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/selected-content/css/selected.content.component.css
  src/modules/universal-discovery/components/selected-content/selected.content.component.js
Labels: bug, enhancement, ready-for-review

#72 EZP-29270: Sub-items sorting order not respected by UDW
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/finder/finder.component.js
  src/modules/universal-discovery/components/finder/finder.tree.branch.component.js
  src/modules/universal-discovery/components/tab-content/create.panel.component.js
  src/modules/universal-discovery/components/tab-content/finder.panel.component.js
  src/modules/universal-discovery/services/universal.discovery.service.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: QA done, bug, ready-for-review

#74 Return of the PropTypes to grace
  .babelrc
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  package.json
  src/modules/sub-items/components/no-items/no.items.component.js
  src/modules/sub-items/sub.items.module.js
  src/modules/universal-discovery/components/content-meta-preview/content.meta.preview.component.js
  src/modules/universal-discovery/components/content-table/content.table.component.js
  src/modules/universal-discovery/components/content-table/content.table.header.component.js
  src/modules/universal-discovery/components/create/choose.content.type.component.js
  src/modules/universal-discovery/components/create/choose.language.component.js
  src/modules/universal-discovery/components/create/create.component.js
  src/modules/universal-discovery/components/finder/finder.tree.branch.component.js
  src/modules/universal-discovery/components/tab-content/create.panel.component.js
  src/modules/universal-discovery/universal.discovery.module.js
  webpack.common.js
Labels: bug, enhancement, ready-for-review

#73 Change Webpack production configuration so that *.map.js files will be generated.
  webpack.common.js
  webpack.dev.js
Labels: enhancement, ready-for-review

#75 EZP-29127: [UDW] Selected items limit shouldn't be displayed with multiple false
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/selected-content/selected.content.component.js
Labels: QA done, bug, ready-for-review

#76 Removed unused files
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/App.js
  src/index.css
  src/index.js
Labels: QA done, enhancement, ready-for-review

#77 EZP-29338: Can select content without information about content image in UDW
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/content-meta-preview/content.meta.preview.component.js
  src/modules/universal-discovery/components/selected-content/css/selected.content.component.css
  src/modules/universal-discovery/universal.discovery.module.js
Labels: bug, ready-for-qa, ready-for-review

#79 EZP-29360: Bookmark button in UDW is placed too low
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/content-meta-preview/css/content.meta.preview.component.css
Labels: QA done, bug, ready-for-review

#81 EZP-29362: Error when deleting bookmark from UDW
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/universal.discovery.module.js
Labels: QA done, bug, ready-for-review
