Repository ezsystems/ezplatform-admin-ui-modules, pull requests merged in 2019-12, with the labels that each got.

#234 EZP-31089: Wrong allowed content types list on object relation(s) fields
  src/modules/universal-discovery/components/create/choose.content.type.component.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: QA approved

#231 EZP-31194: Searching in UDW does not take allowed CT's into account when ezobjectrelation FieldType is used
  src/modules/universal-discovery/components/search/search.component.js
  src/modules/universal-discovery/components/tab-content/search.panel.component.js
  src/modules/universal-discovery/services/universal.discovery.service.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: Bug, QA approved

#227 EZP-31125: Administration interface should respect siteaccess languages settings
  src/modules/sub-items/components/grid-view/grid.view.item.component.js
  src/modules/sub-items/components/table-view/table.view.item.component.js
  src/modules/sub-items/sub.items.module.js
  src/modules/universal-discovery/components/content-meta-preview/content.meta.preview.component.js
  src/modules/universal-discovery/components/content-table/content.table.item.component.js
  src/modules/universal-discovery/components/finder/finder.tree.leaf.component.js
  src/modules/universal-discovery/components/search/search.results.item.component.js
  src/modules/universal-discovery/components/selected-content/selected.content.component.js
  src/modules/universal-discovery/components/selected-content/selected.content.item.component.js
Labels: QA approved

#236 EZP-31185: Restyling grid view in sub items
  Resources/public/scss/modules/sub-items-list/_grid.view.item.scss
  Resources/public/scss/modules/sub-items-list/_grid.view.scss
Labels: QA approved

#238 EZP-31125: Fixed content name rendering in the sub-items list (grid view)
  src/modules/sub-items/components/grid-view/grid.view.item.component.js
Labels: Bug

#219 EZP-31038: As an editor, I want to perform more bulk actions on sub-items
  Resources/public/scss/modules/sub-items-list/_action.btn.scss
  Resources/translations/sub_items.en.xliff
  src/modules/sub-items/services/bulk.service.js
  src/modules/sub-items/services/endpoints.js
  src/modules/sub-items/sub.items.module.js
Labels: QA approved
