Repository ezsystems/ezplatform-admin-ui-modules, pull requests merged in 2019-03, with the labels that each got.

#149 EZP-30187: As an editor I would like content tree to always have expanded current location
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/content-tree/content.tree.module.js
Labels: Feature, Ready for review

#151 EZP-30196: Select a Content Type from UDW -> Create is missing Content Type icons
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/public/scss/modules/universal-discovery/_choose.content.type.scss
  src/modules/universal-discovery/components/create/choose.content.type.component.js
Labels: Improvement, QA approved, Ready for MERGE, Ready for review

#150 EZP-30193: As an editor I would like content tree to "Collapse all" button
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/public/scss/modules/content-tree/_list.item.scss
  Resources/public/scss/modules/content-tree/_main.scss
  Resources/translations/content_tree.en.xliff
  src/modules/content-tree/components/content-tree/content.tree.js
  src/modules/content-tree/content.tree.module.js
  src/modules/content-tree/services/content.tree.service.js
Labels: Feature, Ready for MERGE, Ready for review

#152 EZP-30195: As a developer I would like content tree to use config from the backend
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/public/scss/modules/content-tree/_list.item.scss
  Resources/translations/content_tree.en.xliff
  src/modules/content-tree/components/content-tree/content.tree.js
  src/modules/content-tree/components/list-item/list.item.component.js
  src/modules/content-tree/components/list/list.component.js
  src/modules/content-tree/content.tree.module.js
Labels: Feature, Ready for review

#153 EZP-30188: As an editor I would like content tree to display spinner while loading items
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/public/scss/modules/content-tree/_main.scss
  src/modules/content-tree/components/content-tree/content.tree.js
Labels: Improvement, Ready for review

#154 EZP-30207: "Show more" button does not show in root if not all items are loaded
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/public/scss/modules/content-tree/_list.item.scss
  src/modules/content-tree/components/content-tree/content.tree.js
  src/modules/content-tree/components/list-item/list.item.component.js
  src/modules/content-tree/components/list/list.component.js
Labels: Bug, Ready for review

#155 EZP-30205: As an editor I would like content tree to hold separate state for different users
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/content-tree/content.tree.module.js
Labels: Improvement, Ready for review

#157 EZP-30243: [Content tree] Loading limit reached displayed when collapsed
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/content-tree/components/list-item/list.item.component.js
Labels: Bug, QA approved

#156 EZP-30232: Item highlight is cropped in Content Tree with scroll
  Resources/public/scss/modules/content-tree/_list.scss
Labels: Bug, QA approved

#158 EZP-30280: [Content Tree] Saved tree state does not delete locations deleted on the backend
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/content-tree/content.tree.module.js
Labels: Bug, Ready for QA, Ready for review

#159 EZP-30289: Content Tree does not load when root location has no items
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/content-tree/content.tree.module.js
Labels: Bug, QA approved, Ready for review

#160 EZEE-30310: SearchLimit UDW: UDW search limit function parameter
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/search/search.component.js
  src/modules/universal-discovery/components/tab-content/search.panel.component.js
  src/modules/universal-discovery/services/universal.discovery.service.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: QA approved

#161 EZP-30245: Bulk delete - item is removed to trash, but user gets permission message
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/sub-items/services/bulk.service.js
Labels: Bug, QA approved

#163 EZP-30203: UDW disappears when scroll appears in Finder in folder div
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/finder/css/finder.component.css
  src/modules/universal-discovery/components/finder/finder.component.js
Labels: Bug, QA approved

#164 EZP-30317: Styling updates for Content Tree
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/public/scss/modules/content-tree/_list.scss
  src/modules/content-tree/components/list-item/list.item.component.js
Labels: Bug, QA approved, Ready for review

#167 EZP-30332: [Safari] Bookmark button is not visible before clicking
  Resources/public/scss/modules/universal-discovery/_content.meta.preview.scss
Labels: Bug, QA approved, Ready for review

#166 EZP-30264: No permission message is blinking in UDW
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/universal.discovery.module.js
Labels: Bug, QA approved

#169 EZP-30312: Performing actions from subitems list does not refresh the Content Tree
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/content-tree/content.tree.module.js
  src/modules/sub-items/sub.items.module.js
Labels: Bug, Improvement, QA approved

#168 EZP-30326: As a user I want to see if my search in UDW has no results
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/bookmarks/bookmarks.component.js
  src/modules/universal-discovery/components/content-table/content.table.component.js
  src/modules/universal-discovery/components/content-table/css/content.table.component.css
  src/modules/universal-discovery/components/search/css/search.component.css
  src/modules/universal-discovery/components/search/search.component.js
Labels: Improvement, QA approved, Ready for review

#171 EZP-30356: "Show more" button from Content Tree should be consistent with "Show more" from UDW
  Resources/public/scss/modules/content-tree/_list.item.scss
Labels: Bug, Improvement, QA approved

#172 EZP-30368: As an editor I would like Content Tree to display message when there are no sub-items
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/public/scss/modules/content-tree/_main.scss
  Resources/translations/content_tree.en.xliff
  src/modules/content-tree/components/content-tree/content.tree.js
Labels: Bug, Improvement, Ready for QA, Ready for review

#174 EZP-30341: Needless scroll in UDW
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/finder/css/finder.component.css
  src/modules/universal-discovery/components/finder/finder.component.js
  src/modules/universal-discovery/components/finder/finder.tree.branch.component.js
  src/modules/universal-discovery/components/tab-content/css/create.panel.component.css
Labels: Bug, QA approved, Ready for review

#170 EZP-30346: Broken notifications with html
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/translations/sub_items.en.xliff
  src/modules/sub-items/sub.items.module.js
Labels: QA approved

#173 EZP-30263: replaces deprecated functions
  src/modules/sub-items/components/table-view/table.view.item.component.js
  src/modules/universal-discovery/components/content-meta-preview/content.meta.preview.component.js
Labels: Improvement, QA approved, Ready for review

#175 EZP-30154: Allow UDW configuration decoupled from Content on the Fly
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/universal.discovery.module.js
Labels: Bug

#176 Escape quotation marks inside translation @Desc
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/search/search.component.js
Labels: Bug, Ready for review
