Repository ezsystems/ezplatform-admin-ui-modules, pull requests merged in 2019-06, with the labels that each got.

#194 EZP-30523: (+) button disappears after clicking it in Search tab from UDW
  src/modules/universal-discovery/components/content-table/content.table.item.component.js
Labels: Bug, QA approved

#191 EZP-30578: Upgrade `ezsystems/ezplatform-admin-ui-modules` to use Symfony 4 components
  DependencyInjection/EzPlatformAdminUiModulesExtension.php
  Resources/config/bazinga_js_translation.yaml
  Resources/public/scss/ezplatform-modules.scss
  composer.json
Labels: Improvement

#193 Revert new UDW changes
  .eslintrc.json
  Resources/encore/ez.config.js
  Resources/public/scss/ezplatform-modules.scss
  Resources/public/scss/modules/udw/_main.scss
  Resources/public/scss/modules/udw/tabs/_main.scss
  Resources/public/scss/modules/udw/tabs/browse/_main.scss
  Resources/public/scss/modules/universal-discovery/_selected.content.scss
  jest.config.js
  jest.setup.js
  jest.window.mock.js
  package.json
  src/modules/common/css-class-names/__tests__/css.class.names.test.js
  src/modules/common/css-class-names/css.class.names.js
  src/modules/common/loading-spinner/loading.spinner.component.js
  src/modules/common/popup/popup.component.js
  src/modules/common/rest-info/rest.info.js
  src/modules/udw/__tests__/udw.module.test.js
  src/modules/udw/common/content-meta-preview/bookmark.icon.component.js
  src/modules/udw/common/content-meta-preview/content.image.preview.component.js
  src/modules/udw/common/content-meta-preview/content.meta.preview.component.js
  src/modules/udw/common/content-type-icon/content.type.icon.component.js
  src/modules/udw/common/select-content-button/select.content.button.component.js
  src/modules/udw/common/selected-content/selected.content.component.js
  src/modules/udw/common/selected-content/selected.content.item.component.js
  src/modules/udw/common/tab-content-panel/tab.content.panel.component.js
  src/modules/udw/services/bookmark.service.js
  src/modules/udw/services/universal.discovery.service.js
  src/modules/udw/tabs/base.tab.component.js
  src/modules/udw/tabs/browse/browse.tab.module.js
  src/modules/udw/tabs/browse/components/finder/finder.component.js
  src/modules/udw/tabs/browse/components/finder/finder.load.more.component.js
  src/modules/udw/tabs/browse/components/finder/finder.tree.branch.component.js
  src/modules/udw/tabs/browse/components/finder/finder.tree.leaf.component.js
  src/modules/udw/udw.module.js
Labels: Ready for review
