Repository ezsystems/ezplatform-admin-ui-modules, pull requests merged in 2019-09, with the labels that each got.

#209 EZP-30904: UDW: Sorting settings are ignored for starting location
  src/modules/universal-discovery/components/finder/finder.component.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: QA approved

#207 EZP-30896: Use ContentType Provider instead of deprecated ContentTypeNames
  src/modules/sub-items/components/table-view/table.view.item.component.js
  src/modules/sub-items/sub.items.module.js
  src/modules/universal-discovery/components/content-meta-preview/content.meta.preview.component.js
  src/modules/universal-discovery/components/content-table/content.table.item.component.js
Labels: QA approved

#200 EZP-30736: Introduce GraphQL in Sub-items widget
  Resources/public/scss/modules/sub-items-list/_table.view.scss
  Resources/translations/sub_items.en.xliff
  src/modules/sub-items/components/grid-view/grid.view.component.js
  src/modules/sub-items/components/grid-view/grid.view.item.component.js
  src/modules/sub-items/components/sub-items-list/sub.items.list.component.js
  src/modules/sub-items/components/table-view/table.view.columns.toggler.js
  src/modules/sub-items/components/table-view/table.view.component.js
  src/modules/sub-items/components/table-view/table.view.item.component.js
  src/modules/sub-items/services/bulk.service.js
  src/modules/sub-items/services/endpoints.js
  src/modules/sub-items/services/sub.items.service.js
  src/modules/sub-items/sub.items.module.js
Labels: Improvement, QA approved

#212 EZP-30101: Wrong class for Trash button for bulk delete pop up
  Resources/public/scss/modules/sub-items-list/_main.scss
  src/modules/sub-items/sub.items.module.js
Labels: Bug, QA approved, Ready for review

#211 EZP-30927: Harmonize select item behavior in Content Tree with UDW
  Resources/public/scss/modules/content-tree/_list.item.scss
Labels: Bug, Improvement, QA approved, Ready for review

#213 EZP-30867: Setting priority of sub-items isn't reflected in ordering of the Content Tree
  src/modules/sub-items/sub.items.module.js
Labels: Bug, QA approved, Ready for MERGE

#215 EZP-30972: Make Subitems header checkbox three-state
  src/modules/sub-items/components/table-view/table.view.component.js
  src/modules/sub-items/components/three-state-checkbox/three.state.checkbox.component.js
Labels: Improvement, QA approved

#214 EZP-29816: Make priority column in children list more prominent
  Resources/public/scss/modules/sub-items-list/_table.view.item.scss
  src/modules/sub-items/components/table-view/table.view.item.component.js
Labels: Improvement, QA approved

#216 EZP-30986: Publication and Modification Dates in Sub-items are incorrect
  src/modules/sub-items/components/table-view/table.view.item.component.js
Labels: Bug
