Repository ezsystems/ezplatform-admin-ui-modules, pull requests merged in 2019-02, with the labels that each got.

#132 EZP-29999: As an editor, I want to see custom icons for content types
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/public/scss/modules/sub-items-list/_table.view.item.scss
  Resources/public/scss/modules/sub-items-list/_table.view.scss
  Resources/public/scss/modules/universal-discovery/_content.table.header.scss
  Resources/public/scss/modules/universal-discovery/_content.table.item.scss
  Resources/public/scss/modules/universal-discovery/_finder.tree.leaf.scss
  src/modules/multi-file-upload/components/upload-list/upload.item.component.js
  src/modules/multi-file-upload/components/upload-list/upload.list.component.js
  src/modules/multi-file-upload/components/upload-popup/upload.popup.component.js
  src/modules/multi-file-upload/multi.file.upload.module.js
  src/modules/sub-items/components/grid-view/grid.view.item.component.js
  src/modules/sub-items/components/table-view/table.view.component.js
  src/modules/sub-items/components/table-view/table.view.item.component.js
  src/modules/sub-items/sub.items.module.js
  src/modules/universal-discovery/components/content-meta-preview/content.meta.preview.component.js
  src/modules/universal-discovery/components/content-table/content.table.header.component.js
  src/modules/universal-discovery/components/content-table/content.table.item.component.js
  src/modules/universal-discovery/components/finder/finder.tree.branch.component.js
  src/modules/universal-discovery/components/finder/finder.tree.leaf.component.js
Labels: Feature, QA approved, Ready for review

#139 EZP-30070: As an editor I would like content tree to match design from wireframes
  .eslintrc.json
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/public/scss/modules/_content.tree.scss
  Resources/public/scss/modules/content-tree/_list.item.scss
  Resources/public/scss/modules/content-tree/_list.scss
  Resources/public/scss/modules/content-tree/_main.scss
  src/modules/content-tree/components/list-item/list.item.component.js
  src/modules/content-tree/components/list/list.component.js
  src/modules/content-tree/content.tree.module.js
Labels: Improvement, Ready for review

#140 EZP-30066: As an editor I would like to see current location marked as selected in the content tree
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/public/scss/modules/content-tree/_list.item.scss
  src/modules/content-tree/components/list-item/list.item.component.js
  src/modules/content-tree/components/list/list.component.js
  src/modules/content-tree/content.tree.module.js
Labels: Improvement, Ready for review

#141 EZP-30138 Solr scoring is not taken into account in the UDW search results list order
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/services/universal.discovery.service.js
Labels: Bug, QA approved

#120 EZP-29888: Content Meta Preview appears on Bookmarks tab in UDW
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/finder/finder.component.js
  src/modules/universal-discovery/components/finder/finder.tree.branch.component.js
  src/modules/universal-discovery/services/universal.discovery.service.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: Bug, QA approved, Ready for review

#143 EZP-30065: As an editor I would like content tree to use real data
  Resources/config/bazinga_js_translation.yml
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/public/scss/modules/content-tree/_list.item.scss
  Resources/translations/content_tree.en.xliff
  src/modules/content-tree/components/content-tree/content.tree.js
  src/modules/content-tree/components/list-item/list.item.component.js
  src/modules/content-tree/components/list/list.component.js
  src/modules/content-tree/content.tree.module.js
  src/modules/content-tree/services/content.tree.service.js
Labels: Improvement, Ready for review

#145 Comment out request to backend from Contnet Tree module
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/content-tree/services/content.tree.service.js
Labels: Bug

#146 Restore Content Tree request to /api/ezp/v2/location/tree/load-subitems
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/content-tree/services/content.tree.service.js
Labels: Bug

#138 EZP-30071: Implement responsive table in Sub-items
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/public/scss/modules/_sub.items.list.scss
  Resources/public/scss/modules/sub-items-list/_table.view.columns.toggler.list.element.scss
  Resources/public/scss/modules/sub-items-list/_table.view.columns.toggler.scss
  Resources/public/scss/modules/sub-items-list/_table.view.item.scss
  Resources/public/scss/modules/sub-items-list/_table.view.scss
  src/modules/sub-items/components/table-view/table.view.columns.toggler.js
  src/modules/sub-items/components/table-view/table.view.columns.toggler.list.element.js
  src/modules/sub-items/components/table-view/table.view.component.js
  src/modules/sub-items/components/table-view/table.view.item.component.js
Labels: Feature, Ready for review

#147 EZP-30075: As an editor I would like to be redirected to a location after clicking on it in the content tree
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/content-tree/components/list/list.component.js
Labels: Feature, Ready for review

#144 EZP-30072: As an editor I would like to see the content tree state restored after reloading a page
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/public/scss/modules/content-tree/_list.item.scss
  Resources/public/scss/modules/content-tree/_main.scss
  src/modules/content-tree/components/content-tree/content.tree.js
  src/modules/content-tree/components/list-item/list.item.component.js
  src/modules/content-tree/components/list/list.component.js
  src/modules/content-tree/content.tree.module.js
  src/modules/content-tree/services/content.tree.service.js
Labels: Feature, Ready for review
