Repository ezsystems/ezplatform-admin-ui-modules, pull requests merged in 2019-05, with the labels that each got.

#186 EZP-30530: Create a base for the new UDW
  .babelrc
  .eslintrc.json
  Resources/encore/ez.config.js
  Resources/public/scss/ezplatform-modules.scss
  Resources/public/scss/modules/udw/_main.scss
  jest.config.js
  jest.setup.js
  jest.window.mock.js
  package.json
  src/modules/common/css-class-names/__tests__/css.class.names.test.js
  src/modules/common/css-class-names/css.class.names.js
  src/modules/common/loading-spinner/loading.spinner.component.js
  src/modules/common/popup/popup.component.js
  src/modules/common/rest-info/rest.info.js
  src/modules/udw/__tests__/udw.module.test.js
  src/modules/udw/services/universal.discovery.service.js
  src/modules/udw/tabs/base.tab.component.js
  src/modules/udw/udw.module.js
  webpack.common.js
Labels: Feature, Ready for review

#187 EZP-30525: Convert Browse Tab as a standalone ReactJS module
  .eslintrc.json
  Resources/encore/ez.config.js
  Resources/public/scss/modules/udw/_main.scss
  Resources/public/scss/modules/udw/tabs/_main.scss
  Resources/public/scss/modules/udw/tabs/browse/_main.scss
  Resources/public/scss/modules/universal-discovery/_selected.content.scss
  src/modules/udw/common/content-meta-preview/bookmark.icon.component.js
  src/modules/udw/common/content-meta-preview/content.image.preview.component.js
  src/modules/udw/common/content-meta-preview/content.meta.preview.component.js
  src/modules/udw/common/content-type-icon/content.type.icon.component.js
  src/modules/udw/common/select-content-button/select.content.button.component.js
  src/modules/udw/common/selected-content/selected.content.component.js
  src/modules/udw/common/selected-content/selected.content.item.component.js
  src/modules/udw/common/tab-content-panel/tab.content.panel.component.js
  src/modules/udw/services/bookmark.service.js
  src/modules/udw/tabs/browse/browse.tab.module.js
  src/modules/udw/tabs/browse/components/finder/finder.component.js
  src/modules/udw/tabs/browse/components/finder/finder.load.more.component.js
  src/modules/udw/tabs/browse/components/finder/finder.tree.branch.component.js
  src/modules/udw/tabs/browse/components/finder/finder.tree.leaf.component.js
  src/modules/udw/udw.module.js
  webpack.common.js
Labels: Feature, Ready for review

#180 EZP-30397: Unify JavaScript event names
  src/modules/universal-discovery/components/content-creator/content.creator.component.js
Labels: Improvement, Ready for review

#181 Delete JS build files and webpack config
  .babelrc
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: Improvement, Ready for review

#192 Add createCssClassNames helper
  src/modules/common/helpers/css.class.names.js
Labels: Ready for review
