Repository ezsystems/ezplatform-admin-ui-modules, pull requests merged in 2019-07, with the labels that each got.

#196 Changed variables to SF4 APP_ENV and APP_DEBUG
  .travis.yml
Labels: Ready for review

#197 EZP-30128: Bulk delete - User account partially deleted
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/translations/sub_items.en.xliff
  src/modules/sub-items/services/bulk.service.js
  src/modules/sub-items/sub.items.module.js
Labels: Bug, QA approved

#199 EZP-30128: [Follow-up] Fix Sub-items delete/trash actions' messages
  Resources/translations/sub_items.en.xliff
  src/modules/sub-items/sub.items.module.js
Labels: Bug, QA approved, Ready for MERGE
