Repository ezsystems/ezplatform-admin-ui-modules, pull requests merged in 2019-01, with the labels that each got.

#126 EZP-29994: Move CSS files for Multi File Upload Module to Admin UI
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/public/scss/ezplatform-modules.scss
  Resources/public/scss/modules/_multi.file.upload.scss
  Resources/public/scss/modules/muti-file-upload/_drop.area.scss
  Resources/public/scss/modules/muti-file-upload/_main.scss
  Resources/public/scss/modules/muti-file-upload/_progress.bar.scss
  Resources/public/scss/modules/muti-file-upload/_upload.item.scss
  Resources/public/scss/modules/muti-file-upload/_upload.list.scss
  Resources/public/scss/modules/muti-file-upload/_upload.popup.scss
  src/modules/multi-file-upload/components/drop-area/css/drop.area.component.css
  src/modules/multi-file-upload/components/drop-area/drop.area.component.js
  src/modules/multi-file-upload/components/progress-bar/css/progress.bar.component.css
  src/modules/multi-file-upload/components/progress-bar/progress.bar.component.js
  src/modules/multi-file-upload/components/upload-list/css/upload.item.component.css
  src/modules/multi-file-upload/components/upload-list/upload.item.component.js
  src/modules/multi-file-upload/components/upload-list/upload.list.component.js
  src/modules/multi-file-upload/components/upload-popup/css/upload.popup.component.css
  src/modules/multi-file-upload/components/upload-popup/upload.popup.component.js
  src/modules/multi-file-upload/multi.file.upload.module.js
  webpack.common.js
Labels: Improvement, QA approved

#129 EZP-29995: Move CSS files for Sub Items List Module to Admin UI
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/public/scss/ezplatform-modules.scss
  Resources/public/scss/modules/_sub.items.list.scss
  Resources/public/scss/modules/sub-items-list/_action.btn.scss
  Resources/public/scss/modules/sub-items-list/_grid.view.item.scss
  Resources/public/scss/modules/sub-items-list/_grid.view.scss
  Resources/public/scss/modules/sub-items-list/_main.scss
  Resources/public/scss/modules/sub-items-list/_no.items.scss
  Resources/public/scss/modules/sub-items-list/_table.view.item.scss
  Resources/public/scss/modules/sub-items-list/_table.view.scss
  Resources/public/scss/modules/sub-items-list/_view.switcher.button.scss
  Resources/public/scss/modules/sub-items-list/_view.switcher.scss
  src/modules/sub-items/components/action-btn/action.btn.js
  src/modules/sub-items/components/action-btn/css/action.btn.css
  src/modules/sub-items/components/grid-view/css/grid.view.component.css
  src/modules/sub-items/components/grid-view/css/grid.view.item.component.css
  src/modules/sub-items/components/grid-view/grid.view.component.js
  src/modules/sub-items/components/grid-view/grid.view.item.component.js
  src/modules/sub-items/components/no-items/css/no.items.component.css
  src/modules/sub-items/components/no-items/no.items.component.js
  src/modules/sub-items/components/pagination/pagination.button.component.js
  src/modules/sub-items/components/sub-items-list/css/sub.items.list.component.css
  src/modules/sub-items/components/sub-items-list/sub.items.list.component.js
  src/modules/sub-items/components/table-view/css/table.view.component.css
  src/modules/sub-items/components/table-view/css/table.view.item.component.css
  src/modules/sub-items/components/table-view/table.view.component.js
  src/modules/sub-items/components/table-view/table.view.item.component.js
  src/modules/sub-items/components/view-switcher/css/view.switcher.component.css
  src/modules/sub-items/components/view-switcher/view.switcher.button.component.js
  src/modules/sub-items/components/view-switcher/view.switcher.component.js
  src/modules/sub-items/css/sub.items.module.css
  src/modules/sub-items/sub.items.module.js
Labels: Improvement, QA approved

#131 EZP-29995: Move CSS files for Sub Items List Module to Admin UI
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/public/scss/ezplatform-modules.scss
  Resources/public/scss/modules/_sub.items.list.scss
  Resources/public/scss/modules/sub-items-list/_action.btn.scss
  Resources/public/scss/modules/sub-items-list/_grid.view.item.scss
  Resources/public/scss/modules/sub-items-list/_grid.view.scss
  Resources/public/scss/modules/sub-items-list/_main.scss
  Resources/public/scss/modules/sub-items-list/_no.items.scss
  Resources/public/scss/modules/sub-items-list/_table.view.item.scss
  Resources/public/scss/modules/sub-items-list/_table.view.scss
  Resources/public/scss/modules/sub-items-list/_view.switcher.button.scss
  Resources/public/scss/modules/sub-items-list/_view.switcher.scss
  src/modules/sub-items/components/action-btn/action.btn.js
  src/modules/sub-items/components/action-btn/css/action.btn.css
  src/modules/sub-items/components/grid-view/css/grid.view.component.css
  src/modules/sub-items/components/grid-view/css/grid.view.item.component.css
  src/modules/sub-items/components/grid-view/grid.view.component.js
  src/modules/sub-items/components/grid-view/grid.view.item.component.js
  src/modules/sub-items/components/no-items/css/no.items.component.css
  src/modules/sub-items/components/no-items/no.items.component.js
  src/modules/sub-items/components/pagination/pagination.button.component.js
  src/modules/sub-items/components/sub-items-list/css/sub.items.list.component.css
  src/modules/sub-items/components/sub-items-list/sub.items.list.component.js
  src/modules/sub-items/components/table-view/css/table.view.component.css
  src/modules/sub-items/components/table-view/css/table.view.item.component.css
  src/modules/sub-items/components/table-view/table.view.component.js
  src/modules/sub-items/components/table-view/table.view.item.component.js
  src/modules/sub-items/components/view-switcher/css/view.switcher.component.css
  src/modules/sub-items/components/view-switcher/view.switcher.button.component.js
  src/modules/sub-items/components/view-switcher/view.switcher.component.js
  src/modules/sub-items/css/sub.items.module.css
  src/modules/sub-items/sub.items.module.js
Labels: QA approved

#125 EZEE-2660: 500 error occurs when publishing form in form on the fly
  .prettierrc
  Resources/public/js/MultiFileUpload.module.js
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  package.json
  src/modules/common/popup/popup.component.js
  src/modules/multi-file-upload/components/upload-list/upload.list.component.js
  src/modules/sub-items/sub.items.module.js
  src/modules/universal-discovery/components/content-creator/content.creator.component.js
  src/modules/universal-discovery/components/content-creator/css/content.creator.component.css
  src/modules/universal-discovery/components/content-table/content.table.item.component.js
  src/modules/universal-discovery/components/search/search.pagination.component.js
  src/modules/universal-discovery/components/selected-content/selected.content.component.js
  src/modules/universal-discovery/services/bookmark.service.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: Bug, Ready for review

#134 EZP-30021: Inactive UDW tabs have wrong background colour
  Resources/public/scss/modules/universal-discovery/_content.table.header.scss
  Resources/public/scss/modules/universal-discovery/_tab.nav.item.scss
Labels: Bug, QA approved

#136 EZP-30064: As an editor I would like to view a content tree in location view
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/public/scss/ezplatform-modules.scss
  Resources/public/scss/modules/_content.tree.scss
  Resources/public/scss/modules/content-tree/_list.item.scss
  src/modules/content-tree/components/list-item/list.item.component.js
  src/modules/content-tree/components/list/list.component.js
  src/modules/content-tree/content.tree.module.js
  webpack.common.js
Labels: Feature, Ready for QA, Ready for review

#135 EZP-30042: I can see fine grey lines in Bookmark & Search tables in UDW
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js
  Resources/public/js/UniversalDiscovery.module.js.map
  src/modules/universal-discovery/components/content-table/css/content.table.header.component.css
Labels: Bug, QA approved, Ready for MERGE

#137 EZP-30069: As an editor I would like to change manually the width of content tree panel
  Resources/public/js/ContentTree.module.js
  Resources/public/js/ContentTree.module.js.map
  Resources/public/js/MultiFileUpload.module.js.map
  Resources/public/js/SubItems.module.js.map
  Resources/public/js/UniversalDiscovery.module.js.map
  Resources/public/scss/modules/_content.tree.scss
  Resources/public/scss/modules/content-tree/_main.scss
  src/modules/content-tree/content.tree.module.js
Labels: Feature, Ready for review
