Repository ezsystems/ezplatform-admin-ui-modules, pull requests merged in 2020-03, with the labels that each got.

#276 EZP-31416: Remove selection bar on the right from UDW (Browse)
  src/modules/universal-discovery/components/selected-locations/selected.locations.js
  src/modules/universal-discovery/content.meta.preview.module.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: QA approved

#277 EZP-31430: Can't select existing object for ImageAsset field
  src/modules/universal-discovery/services/universal.discovery.service.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: Bug, QA approved

#280 EZP-31220: Migrated codebase to Symfony 5
  composer.json
  src/modules/universal-discovery/components/content-edit-button/content.edit.button.js
Labels: Ready for MERGE

#282 EZEE-2982: Avoided creating draft when user is edited
  src/modules/universal-discovery/components/content-edit-button/content.edit.button.js
Labels: QA approved

#278 EZP-31417: Added tooltips to UDW
  Resources/translations/universal_discovery_widget.en.xliff
  src/modules/universal-discovery/components/content-create-button/content.create.button.js
  src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
  src/modules/universal-discovery/components/content-edit-button/content.edit.button.js
  src/modules/universal-discovery/components/content-table/content.table.js
  src/modules/universal-discovery/components/finder/finder.leaf.js
  src/modules/universal-discovery/components/menu-button/menu.button.js
  src/modules/universal-discovery/components/selected-locations/selected.locations.item.js
  src/modules/universal-discovery/components/selected-locations/selected.locations.js
  src/modules/universal-discovery/components/sort-switcher/sort.switcher.js
  src/modules/universal-discovery/components/toggle-selection-button/toggle.selection.button.js
  src/modules/universal-discovery/components/view-switcher/view.switcher.js
  src/modules/universal-discovery/content.meta.preview.module.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: QA approved

#284 EZP-31070: Missing message in Browse tab in UDW when starting location is empty
  Resources/public/scss/modules/universal-discovery/_bookmarks.scss
  Resources/public/scss/modules/universal-discovery/_finder.scss
  Resources/translations/search.en.xliff
  Resources/translations/universal_discovery_widget.en.xliff
  src/modules/universal-discovery/components/finder/finder.component.js
Labels: QA approved

#285 EZP-31408: 'This Location has no Sub-items' msg is displayed above location
  Resources/public/scss/modules/content-tree/_list.scss
  Resources/public/scss/modules/content-tree/_main.scss
  src/modules/content-tree/components/content-tree/content.tree.js
  src/modules/content-tree/components/list/list.component.js
Labels: QA approved
