Repository ezsystems/ezplatform-admin-ui-modules, pull requests merged in 2020-02, with the labels that each got.

#255 EZP-29157: Disabled MFU popup when UDW is open
  src/modules/multi-file-upload/multi.file.upload.module.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: Bug, QA approved

#257 EZP-30909: Form created On the Fly should take full modal view
  Resources/public/scss/modules/universal-discovery/_content.create.scss
  src/modules/universal-discovery/content.create.tab.module.js
Labels: QA approved

#258 EZP-31343: Added sorting asc/desc to items of udw
  Resources/public/scss/modules/universal-discovery/_sort.switcher.scss
  src/modules/universal-discovery/components/sort-switcher/sort.switcher.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: QA approved

#261 EZP-31335: Pagination is displayed for first page of results
  src/modules/common/pagination/pagination.js
  src/modules/sub-items/sub.items.module.js
Labels: Bug, QA approved

#262 EZP-31334: Intermediate states are displayed in UDW
  src/modules/universal-discovery/services/universal.discovery.service.js
Labels: Bug, QA approved

#265 EZP-31375: UDW tabs doesn't respect the items per page config
  src/modules/universal-discovery/bookmarks.tab.module.js
  src/modules/universal-discovery/browse.tab.module.js
  src/modules/universal-discovery/components/bookmarks-list/bookmarks.list.js
  src/modules/universal-discovery/components/finder/finder.branch.js
  src/modules/universal-discovery/components/finder/finder.js
  src/modules/universal-discovery/components/grid-view/grid.view.js
  src/modules/universal-discovery/components/search/search.js
  src/modules/universal-discovery/search.tab.module.js
Labels: Bug, QA approved

#264 EZP-31367: Content tree should display the root location of the section
  Resources/public/scss/modules/content-tree/_list.item.scss
  src/modules/content-tree/components/list-item/list.item.component.js
Labels: Bug, QA approved

#256 Revert "EZP-31314: Updated animation for content tree"
  Resources/public/scss/modules/content-tree/_list.item.scss
Labels: Ready for MERGE

#266 EZP-31376: Sub-items paginations are visible if there are no items
  src/modules/common/pagination/pagination.js
Labels: Bug, QA approved

#263 EZP-31355: When browsing in UDW children view is blocked by content meta preview
  src/modules/universal-discovery/components/finder/finder.js
Labels: Bug, QA approved

#268 EZP-31324: UDW typography and color design updates
  Resources/public/scss/modules/universal-discovery/_bookmarks.list.scss
  Resources/public/scss/modules/universal-discovery/_breadcrumbs.scss
  Resources/public/scss/modules/universal-discovery/_content.create.widget.scss
  Resources/public/scss/modules/universal-discovery/_content.meta.preview.scss
  Resources/public/scss/modules/universal-discovery/_finder.branch.scss
  Resources/public/scss/modules/universal-discovery/_finder.leaf.scss
  Resources/public/scss/modules/universal-discovery/_grid.item.scss
  Resources/public/scss/modules/universal-discovery/_main.scss
  Resources/public/scss/modules/universal-discovery/_sort.switcher.scss
  Resources/public/scss/modules/universal-discovery/_tab.scss
  Resources/public/scss/modules/universal-discovery/_tab.selector.scss
  src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
Labels: Bug, QA approved

#271 EZP-31327: Update animation for UDW slide panels
  Resources/public/scss/modules/universal-discovery/_content.create.widget.scss
  Resources/public/scss/modules/universal-discovery/_content.meta.preview.scss
  Resources/public/scss/modules/universal-discovery/_selected.locations.scss
  src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
  src/modules/universal-discovery/components/tab/tab.js
  src/modules/universal-discovery/content.meta.preview.module.js
Labels: QA approved

#269 EZP-31310: Fixed VersionDraftConflict for content having multiple locations
  src/modules/sub-items/components/table-view/table.view.item.component.js
Labels: Bug, QA approved, Ready for review

#270 EZP-31345 Added language select when user edit sub items
  Resources/public/scss/modules/_sub.items.list.scss
  Resources/public/scss/modules/sub-items-list/_language.selector.scss
  Resources/translations/sub_items.en.xliff
  src/modules/sub-items/components/sub-items-list/instant.filter.component.js
  src/modules/sub-items/components/sub-items-list/language.selector.compoment.js
  src/modules/sub-items/components/table-view/table.view.component.js
  src/modules/sub-items/components/table-view/table.view.item.component.js
Labels: QA approved

#246 EZP-31236: Added bootstrap tooltip for all nodes with attribute title
  Resources/public/scss/modules/sub-items-list/_table.view.item.scss
  Resources/translations/sub_items.en.xliff
  src/modules/sub-items/components/action-btn/action.btn.js
  src/modules/sub-items/components/table-view/table.view.columns.toggler.js
  src/modules/sub-items/components/table-view/table.view.item.component.js
  src/modules/sub-items/sub.items.module.js
Labels: QA approved

#273 EZP-31402: Cannot navigate in UDW grid view
  src/modules/universal-discovery/components/breadcrumbs/breadcrumbs.js
Labels: Bug, QA approved

#274 EZP-31400: changed Name to TranslatedName
  src/modules/universal-discovery/components/bookmarks-list/bookmarks.list.js
  src/modules/universal-discovery/components/breadcrumbs/breadcrumbs.js
  src/modules/universal-discovery/components/content-table/content.table.item.js
  src/modules/universal-discovery/components/filters/filters.js
  src/modules/universal-discovery/components/finder/finder.branch.js
  src/modules/universal-discovery/components/finder/finder.leaf.js
  src/modules/universal-discovery/components/grid-view/grid.view.item.js
  src/modules/universal-discovery/components/selected-locations/selected.locations.item.js
  src/modules/universal-discovery/content.meta.preview.module.js
Labels: Ready for QA
