Repository ezsystems/ezplatform-admin-ui-modules, pull requests merged in 2020-01, with the labels that each got.

#244 EZP-31259: Missing translation for languageCodes.length in UDW
  src/modules/universal-discovery/content.meta.preview.module.js
Labels: Bug, QA approved

#242 EZP-31262: Inconsistency in Search results table style
  Resources/public/scss/modules/universal-discovery/_content.table.scss
Labels: Bug, QA approved

#243 EZP-31260: Double clicking on the location without children disappears the preview in UDW
  src/modules/universal-discovery/components/finder/finder.leaf.js
Labels: Bug, QA approved

#247 EZP-31256: Items list is not refreshed in new UDW when using content on the fly
  src/modules/universal-discovery/content.create.tab.module.js
Labels: Bug, QA approved

#248 EZP-31289: Create button is active before selecting location
  src/modules/universal-discovery/bookmarks.tab.module.js
  src/modules/universal-discovery/components/content-create-button/content.create.button.js
  src/modules/universal-discovery/content.meta.preview.module.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: Bug, QA approved

#249 EZP-31294: Location items are not visible in UDW grid view
  src/modules/universal-discovery/components/breadcrumbs/breadcrumbs.js
Labels: Bug, QA approved

#250 EZEE-2956: Auto confirm is not enabled in UDW for Embed block
  src/modules/universal-discovery/components/content-create-button/content.create.button.js
  src/modules/universal-discovery/content.create.tab.module.js
Labels: Bug, QA approved

#245 EZP-29767: Added overflow to popup when it's partially hidden
  src/modules/common/tooltip-popup/tooltip.popup.component.js
Labels: QA approved

#253 EZP-31027: Disabled language is available in COTF
  src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
Labels: Bug, QA approved, Ready for MERGE

#252 EZP-31027: Disabled language is available in COTF
  src/modules/universal-discovery/components/create/choose.language.component.js
Labels: Bug, QA approved, Ready for MERGE

#254 EZP-31314: Updated animation for content tree
  Resources/public/scss/modules/content-tree/_list.item.scss
Labels: Improvement, QA approved, Ready for QA

#251 EZP-31261: UDW tree is not loaded properly when switching from Bookmarks tab
  Resources/translations/universal_discovery_widget.en.xliff
  src/modules/universal-discovery/bookmarks.tab.module.js
  src/modules/universal-discovery/components/breadcrumbs/breadcrumbs.js
  src/modules/universal-discovery/components/content-table/content.table.item.js
  src/modules/universal-discovery/components/finder/finder.branch.js
  src/modules/universal-discovery/components/grid-view/grid.view.js
  src/modules/universal-discovery/content.create.tab.module.js
  src/modules/universal-discovery/hooks/useFindLocationsByParentLocationIdFetch.js
  src/modules/universal-discovery/services/universal.discovery.service.js
  src/modules/universal-discovery/universal.discovery.module.js
Labels: Bug, QA approved
